# Generated by Django 4.2 on 2024-07-28 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_event', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('initial_date', models.DateField()),
                ('end_date', models.DateField()),
                ('program', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_activity', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='events.event')),
            ],
        ),
    ]
