# Generated by Django 4.2 on 2024-12-31 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_event', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('initial_date', models.DateField()),
                ('end_date', models.DateField()),
                ('logo', models.ImageField(null=True, upload_to='events/logos/', verbose_name='Event Logo')),
                ('program', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Sponsor Name')),
                ('link', models.URLField(max_length=500, verbose_name='Sponsor Link')),
                ('logo', models.ImageField(upload_to='sponsors/logos/', verbose_name='Sponsor Logo')),
                ('tier', models.CharField(choices=[('diamante', 'Diamante'), ('platino', 'Platino'), ('oro', 'Oro'), ('plata', 'Plata'), ('patrocinador', 'Patrocinador')], default='patrocinador', max_length=12, verbose_name='Sponsor Tier')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_sponsors', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_room', models.CharField(max_length=250)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event/images/', verbose_name='Event Images')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_activity', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('description', models.TextField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('author', models.CharField(default='-', max_length=250)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_activities', to='events.event')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_activities', to='events.room')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_activities', to='events.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'activity')},
            },
        ),
    ]
