# Generated by Django 4.2 on 2024-08-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_room_event_alter_activity_event_alter_activity_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='author',
            field=models.CharField(default='-', max_length=250),
        ),
    ]
