# Generated by Django 4.2 on 2024-08-11 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_activity_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Sponsor Name')),
                ('link', models.URLField(max_length=500, verbose_name='Sponsor Link')),
                ('logo', models.ImageField(upload_to='sponsors/logos/', verbose_name='Sponsor Logo')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_sponsors', to='events.event')),
            ],
        ),
    ]
