# Generated by Django 4.2 on 2024-08-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='tier',
            field=models.CharField(choices=[('diamante', 'Diamante'), ('platino', 'Platino'), ('plata', 'Plata'), ('patrocinador', 'Patrocinador')], default='patrocinador', max_length=12, verbose_name='Sponsor Tier'),
        ),
    ]
